platform :ios, '10.0'

#source 'https://github.com/CocoaPods/Specs.git'

target 'WeatherApp' do
	use_frameworks!
    pod 'BSNetworking', path: 'LocalPods/BSNetworking'

    target 'WeatherAppTests' do
    	inherit! :search_paths  
  	end
end
